name: SCL-metal

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    env:
        # post the event to the remote action on the following branch
        TESTENV_METAL_BRANCH: master
    steps:
    - uses: actions/checkout@v2
    - name: Run trigger script
      run:  echo "Trigger build for ${GITHUB_SHA}";
            /bin/sh .github/events/trigger_build_test.sh
            ${TESTENV_METAL_BRANCH}
            ${GITHUB_SHA}
            ${{ secrets.TESTENV_METAL_EVENT_USERNAME }}
            ${{ secrets.TESTENV_METAL_EVENT_TOKEN }}

